apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: glahvl50l-python
  janus-idp.io/tekton: glahvl50l-python
  backstage.io/kubernetes-id: glahvl50l-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: glahvl50l-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
